openshift-kni/commatrix

endpointslices/endpointslices.go
endpointslices/endpointslices_test.go

The name of the pod was the service name

Fix the pod name in the matrix

---

commatrix/commatrix.go

This PR changes the function that creates a comDetails list from a file to be public, to allow using it in origin tests.
The function name has also been refactored from "AddFromFile" to "GetComDetailsListFromFile" to clarify the purpose of the function.

Convert commatrix creation from file function to public

---

cmd/main.go
commatrix/generate.go
consts/consts.go
samples/custom-entries/example-custom-entries.csv
samples/custom-entries/example-custom-entries.json
samples/custom-entries/example-custom-entries.yaml
types/types.go

The node role header of a commatrix in the csv format, defers from those of types json and yaml (`Node Role` instead of `nodeRole`). So, csv annotations in `ComDetails` struct were added.
The previous custom entries examples had some incorrect parameters which were fixed:
1. example-custom-entries.csv: `NodeRole` column was changed to `Node Rule` (as in the documented commatrix.
2. example-custom-entries.yaml and example-custom-entries.json: port was changed from a string to an int (9050 instead of "9050" for example).
a unit test applying the custom entries samples will be added in a separate PR.

Allow generating commatrix from csv and fix samples

---

pkg/commatrix-creator/commatrix.go

Convert `getComDetailsListFromFile` func to public in order to use it in the origin repo.

Convert get details from file to public

---

pkg/commatrix-creator/commatrix.go

The creation of a new `CommunicationMatrixCreator` had inserted the `customEntriesFormat` and `customEntriesPath` in the wrong order. This PR replace their order to enable a correct creation of the of the object and also specifies the inserted fields names to avoid confusion.
In addition the description of the `New` function was suited an older version that has created a new ComMatrix, so there for was moved to describe the method `CreateEndpointMatrix`.

Fix CommunicationMatrixCreator New func params insertion order

---

pkg/types/types.go

make func separateMatrixByRole public for origin repo use
for now i rewrite it on origin so i will use this public when it will be merge

make func separateMatrixByRole public for origin repo use

---

pkg/types/static-custom-entries.go

The port is open on the node but doesn't have an endpointslice.

Add csi-node-driver port to static entries

---

pkg/endpointslices/endpointslices.go
pkg/listening-sockets/listening-sockets.go
pkg/types/types.go

We should return a single node role per node to avoid duplicating the matrix with the same ports on different node roles while listening on the same node (for example, in SNO, which has multiple roles on a single node).

Fix GetNodeRole func to return a single node role per node

---

cmd/main.go
pkg/commatrix-creator/commatrix.go
pkg/listening-sockets/listening-sockets.go
pkg/types/types.go

This PR modifies ComMatrix method `GenerateMatrixDiff` to generate an organized diff using the `CleanComDetails` method sorting logic.
The updated `GenerateMatrixDiff` method works as follows:
1. Calling `generateUnitedMatrix` method to unite two matrices (without duplications).
2. Sorting the United matrix using `CleanComDetails` method.
3. Calling `mapDiffBetweenMatrices` method mark the diff between the matrices using a map.
4. Iterating over the **sorted** United matrix and generate the diff:  a `+` or  `-` sign (or a nothing) will be added to the each cd according to the marking done in previous (3) step.

Sort matrix diff entries order

---

Makefile
cmd/main.go
pkg/commatrix-creator/commatrix.go
pkg/types/static-custom-entries.go
pkg/types/types.go

Addressing [this](https://github.com/openshift/origin/pull/28946#discussion_r1720396672) comment in the origin repo. As `MNO` is not a standard name for "Not SNO", we changed the type name to be `Standard`.

Change MNO deployment type to Standard type

---

pkg/matrix-diff/matrix-diff.go
pkg/types/types.go

This PR removes the `Diff` Method of the `ComMatrix` struct was removed, since it is not necessary when having the `MatrixDiff` struct which represents the diff between two comMatrices.
Also, comments were added to the `MatrixDiff` struct to make it's components and purpose clearer.

Remove Diff method from ComMatrix struct

---

pkg/endpointslices/endpointslices.go

The service name should be printed to the matrix, not its namespace.

Fix service record info

---

cmd/main.go
pkg/listening-sockets/listening-sockets.go
pkg/listening-sockets/listening_sockets_test.go
test/e2e/commatrix_suite_test.go
test/pkg/firewall/firewall.go
test/pkg/node/node.go

This test validates the ports in a generated communication matrix match a snapshot of the node's listening ports (created with the Linux `ss` utility)

Add a test to validate the Communication Matrix matches 'ss'

---

test/e2e/nftables_test.go
test/pkg/cluster/cluster.go

update the wait for mc to wait just if it a new mc or its a real update on the mc
for now if there is an update that is not a real update( like run with same configuration), the code will stuck to wait for the mcp to start update and this is not a good behavior

update the wait for mc to wait just if it a new mc or its a real update on the mc

---

test/e2e/validation_test.go

The documented communication matrix, starting from version 4.18, has been moved under the commatrix repo.
Hence the e2e test comparing between the generated (endpoint slice) commatrix to the documented commatrix of version 4.18 and above, should use the new URL.

Use new documented commatrix URL in validation e2e test

---

test/e2e/nftables_test.go
test/pkg/node/node.go

When we try to get a node in an SNO cluster that is in "NotReady" state, we will get a "connection refused" error.
Because of that, when trying to confirm that a node is in a "NotReady" state in an SNO cluster, instead of checking nodes condition we would like to check if the error returned from when trying to get the node is indeed "connection refused". If so, we can assume that the node is in "NotReady" state.

Handle WaitForNodeNotReady for SNO use

---

docs/stable/raw/bm.csv
docs/stable/unique/bm.csv

This PR adds port 6388 to the bm documented commatrix based on the failures of [nightly-4.18-telco5g-network-flow-matrix-bm](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-telco5g-network-flow-matrix-bm/1888000033740034048) and [nightly-4.19-telco5g-network-flow-matrix-bm](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-telco5g-network-flow-matrix-bm/1888000045475696640) runs.
This change should be updated in both release-4.19 and release-4.18 branches.

Add port 6388 to bm documented commatrix

---

docs/stable/raw/bm.csv
docs/stable/unique/bm.csv

As there were some merge conflicts, [PR#96](https://github.com/openshift-kni/commatrix/pull/96) was cherry-picked locally.

[release-4.18] Add port 6388 to bm documented commatrix

---

docs/stable/raw/bm.csv
docs/stable/unique/bm.csv
pkg/types/static-custom-entries.go

As there were some merge conflicts, [PR#110](https://github.com/openshift-kni/commatrix/pull/110) was cherry-picked locally.

[release-4.18] Remove ports 5050 and 9447 from docs

---

pkg/types/static-custom-entries.go

Port 5050 has been removed from 4.17 documented commatrix (see [PR](https://github.com/openshift/openshift-docs/pull/90465)) as it is no open on that version. Hence, it can now be removed from static entries of 4.17.

[release-4.17] Remove port 5050 from static entries

---

Makefile
cmd/README.md
cmd/generate/generate.go
cmd/generate/generate_test.go
pkg/commatrix-creator/commatrix.go
pkg/commatrix-creator/commatrix_test.go
pkg/types/types.go
test/e2e/e2e_suite_test.go

add a new required flag 
- added a new string var platform-type  (baremetal,aws). required.
- update the readme with the new flag and examples
- update the makefile to use the new var
- update the validation function to handle errors on the new var
- make it as required failed if not set
- update the unittest of the generate class
- change the infra var from Cloud to AWS
- add a missing compare to errors on the unitest

add a new required  flag for the platfrom type

---

pkg/commatrix-creator/commatrix.go
pkg/endpointslices/endpointslices.go
pkg/endpointslices/filter.go

As it is now, when creating the endpointslices communication matrix, we filter the ports which are are not associate with a NodePort or a LoadBalancer service and that are not specified as `hostNetwork: true` in the pod's sped - The purpose is to append to the communication matrix, only ports that are exposed externally.
Another way to check if a port is exposed externally, is to check whether is has a hostPort - meaning the container’s port is directly bind to a specific port on the node.
This PR adds a filter that checks whether a container port is associated with a hostPort - if so it will be added to the communication matrix as it means it is an exposed port.

Filter hostPort ports for inclusion in generated endpointslice commatrix

---

pkg/commatrix-creator/commatrix.go
pkg/types/types.go
test/e2e/e2e_suite_test.go
test/e2e/nftables_test.go
test/e2e/validation_test.go

- use the oc command to generate the matric's and read them, for simulate for user running.
- Create a `ParseToComDetailsList` function to refactor the process of loading `ComDetailsList` from files, removing reliance on the `commMatrixCreator`.
- This refactor improves the e2e test by making it closer to user behavior and centralizing the parsing logic for better reuse and maintainability.
- Replaced internal matrix generation functions with the OpenShift CLI (oc) commands to generate and retrieve matrices, aligning the test process with actual user interactions.

refactor e2e test

---

pkg/commatrix-creator/commatrix.go
pkg/commatrix-creator/commatrix_test.go
pkg/matrix-diff/matrix-diff.go
test/e2e/validation_test.go

- export GetStaticEntries for external use
the getStaticEntries function has been exported (made public) by renaming it to GetStaticEntries, allowing it to be used in other package
- create a GetCommonEntries to return the common entries on a matrix
Create GetCommonEntries to return entries shared by both matrices in a diff
- Renamed GenerateUniquePrimary and GenerateUniqueSecondary to GetUniquePrimary and GetUniqueSecondary for better clarity, since the functions return values rather than generate the

export GetStaticEntries for external use and add GetCommonEntries function on diff package

---

Makefile
cmd/README.md
cmd/generate/generate.go
cmd/generate/generate_test.go
pkg/commatrix-creator/commatrix.go
pkg/commatrix-creator/commatrix_test.go
pkg/types/types.go
pkg/utils/mock/mock_utils.go
pkg/utils/utils.go
test/e2e/e2e_suite_test.go

We originally introduced the PLATFORM_TYPE environment variable to handle cases where the platform type was None. However, None is a valid platform type on its own and should not be interpreted as either a cloud or baremetal platform.
Therefore, we are removing all usage of the PLATFORM_TYPE variable and will rely solely on the existing functions that detect the platform type automatically.
update the code to handle the none platfrom type:
- on case of test need to compare the none sno to the bm sno
- on the static entries no need to add for none
- remove the env iota var and use the configv1 var
- supported telco cases for now are (bm sno thats none and bm mno and the aws)
change the d var to be deployment a clear name

handle the noneplatformtype platform (removing the added platform-type var and add the support of none in the code)

---

cmd/generate/generate_test.go
docs/stable/raw/aws-sno.csv
docs/stable/raw/aws.csv
docs/stable/raw/bm-sno.csv
docs/stable/unique/aws-sno.csv
docs/stable/unique/aws.csv
docs/stable/unique/bm-sno.csv
pkg/commatrix-creator/commatrix.go
pkg/commatrix-creator/commatrix_test.go
pkg/types/static-custom-entries.go
test/e2e/validation_test.go

Ports 10300, 10390 had been changed to be used only internally and there for shouldn't be documented in the communication matrix (see resolved [JIRA bug](https://issues.redhat.com/browse/OCPBUGS-50493), and [PR](https://github.com/openshift/csi-operator/pull/364) converting the ports to internal use)
Note: `types.CloudStaticEntriesWorker` was deleted as it only contained the above ports.

Remove ports 10300 and 10390 from doc commatrix and static entries

---

test/e2e/e2e_suite_test.go
test/e2e/validation_test.go

The current test is based on the old commatrix docs format the included only one matrix. Hence, we exclude static entries with platform and deployment types, that differ from the ones the cluster the test is running on has, from the documented commatrix when comparing it to the generated one. 
The new version (4.18 and above) contains matrices by platform type and deployment, and each cluster is compared to the corresponding matrix. As a results,  the exclusion of the static entries by deployment and platform types from the documented commatrix is not needed.

Update test validates the commatrix in OCP docs is up-to-date

---

docs/stable/raw/bm-sno.csv
docs/stable/unique/bm-sno.csv

Ports 10258 and 10260 were added to the commatrix as a results of missmatching the bm sno cluster to the right platform type. This PR updates th bm sno commatrix to match a sno none type cluster exactly.

Update bm sno commatrix to match sno none type cluster

---

docs/stable/raw/bm.csv
docs/stable/unique/bm.csv
pkg/types/static-custom-entries.go

port are expose but dont have endpointslice from 4.19+ need to add it to the static entry list

add missing port on bm 9454 to static entries and bm documentation

---

test/e2e/e2e_suite_test.go
test/e2e/validation_test.go

The current test is based on the old commatrix docs format the included only one matrix. Hence, we exclude static entries with platform and deployment types, that differ from the ones the cluster the test is running on has, from the documented commatrix when comparing it to the generated one. The new version (4.18 and above) contains matrices by platform type and deployment, and each cluster is compared to the corresponding matrix. As a results, the exclusion of the static entries by deployment and platform types from the documented commatrix is not needed.
This PR was manually cherry picked from [PR#127](https://github.com/openshift-kni/commatrix/pull/127), as there were merge conflicts.

[release-4.18] Update test validates the commatrix in OCP docs is up-to-date

---

docs/stable/raw/bm-sno.csv
docs/stable/unique/bm-sno.csv

Ports 10258, 10260, 10300 and 10309  were added to the commatrix as a results of missmatching the bm sno cluster to the right platform type. This PR updates th bm sno commatrix to match a sno none type cluster exactly.

[release-4.18] Update bm sno commatrix to match sno none type cluster

---

cmd/generate/generate.go
pkg/types/types.go
pkg/utils/utils.go
test/e2e/e2e_suite_test.go
test/e2e/validation_test.go

Instead of checking if the cluster's platform type is supported within the `GetPlatformType` function, we will check and handle the platform type out side of the function to avoid the assumption the function is always called in order to get the platform type.
Also if cluster's platform type is not supported, the e2e tests will be
skipped.

Improve supported cluster's platform type check

---

pkg/types/static-custom-entries.go

Port 9537 is not exposed and hence was removed from documented commatrix (see [PR#93895](https://github.com/openshift/openshift-docs/pull/93895)). Therefore, it should be removed from static entries as well.

[release-4.17] Remove port 9537 from static entries

---

docs/stable/raw/none-sno.csv
docs/stable/unique/none-sno.csv
test/e2e/validation_test.go

This PR is the first of changing the bm-sno commmatrix name to none-sno. after this PR will be merged, the pointer to the commatrix in the official documentation will be changed, and than we can remove the commatrix under the name bm-sno.
This PR was manully cherry picked from [PR#139](https://github.com/openshift-kni/commatrix/pull/139)

[release-4.18] Duplicate bm-sno commatrix under the name none-sno

---

Dockerfile

This PR creates a Dockerfile that builds the commatrix binary in order to use the commatrix plugin in the origin tests. After the merge of this PR we will add a prow configuration in the release repo in order to build the image and promote it using the ci operator, and than use the build image as a base image for building the origin's repo podman that runs the origin tests (see [dockerfile](https://github.com/openshift/origin/blob/main/images/tests/Dockerfile.rhel)) so the it will contain the necessary plugin.

Create a Dockerfile that builds commatrix binary
